//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMax.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class gl_accbranchs
    {
        public int abid { get; set; }
        public Nullable<int> abvalue { get; set; }
        public string abname { get; set; }
        public Nullable<int> bchartid { get; set; }
        public string notes { get; set; }
        public Nullable<int> branchid { get; set; }
        public Nullable<int> modid { get; set; }
        public string modname { get; set; }
    
        public virtual gl_chart gl_chart { get; set; }
    }
}
