//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMax.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class gl_accpay
    {
        public int accpayid { get; set; }
        public Nullable<int> paytypeid { get; set; }
        public string paytypename { get; set; }
        public Nullable<int> branchid { get; set; }
        public Nullable<int> paychartid { get; set; }
        public string paychartname { get; set; }
    }
}
