//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMax.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class gl_chart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gl_chart()
        {
            this.gl_accbranchs = new HashSet<gl_accbranchs>();
            this.gl_vocherdtls = new HashSet<gl_vocherdtls>();
            this.s_customers = new HashSet<s_customers>();
        }
    
        public int chartid { get; set; }
        public Nullable<long> chartcode { get; set; }
        public string chartname { get; set; }
        public Nullable<int> nodeid { get; set; }
        public Nullable<int> levelno { get; set; }
        public string levelnoname { get; set; }
        public Nullable<bool> leger { get; set; }
        public Nullable<decimal> balance { get; set; }
        public Nullable<int> acctype { get; set; }
        public string acctypename { get; set; }
        public string fulltree { get; set; }
        public Nullable<int> accnature { get; set; }
        public string accnaturename { get; set; }
        public Nullable<int> branchid { get; set; }
        public string branchname { get; set; }
        public string chartename { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gl_accbranchs> gl_accbranchs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gl_vocherdtls> gl_vocherdtls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<s_customers> s_customers { get; set; }
    }
}
