//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMax.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class gl_vouchers
    {
        public int vchrid { get; set; }
        public string vchrno { get; set; }
        public string vchrdocno { get; set; }
        public Nullable<System.DateTime> vchrdate { get; set; }
        public Nullable<int> branchid { get; set; }
        public string branchname { get; set; }
        public string vchrdesc { get; set; }
        public string vuser { get; set; }
        public Nullable<bool> postacc { get; set; }
        public string puser { get; set; }
        public Nullable<int> vchrtype { get; set; }
        public string vchrtypename { get; set; }
        public Nullable<bool> uservchr { get; set; }
        public string fyear { get; set; }
        public string vrfrance { get; set; }
        public string docpath { get; set; }
    }
}
