//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMax.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hr_employees()
        {
            this.hr_vactions = new HashSet<hr_vactions>();
        }
    
        public int empid { get; set; }
        public string empcode { get; set; }
        public string empname { get; set; }
        public string empmob { get; set; }
        public string embemail { get; set; }
        public string empadd { get; set; }
        public string empidno { get; set; }
        public Nullable<System.DateTime> empbdate { get; set; }
        public string emppic { get; set; }
        public string empnotes { get; set; }
        public string eduname { get; set; }
        public Nullable<int> branchid { get; set; }
        public string branchname { get; set; }
        public Nullable<int> ccid { get; set; }
        public string ccname { get; set; }
        public Nullable<int> nationid { get; set; }
        public string nationname { get; set; }
        public Nullable<int> nationtype { get; set; }
        public Nullable<int> jobid { get; set; }
        public string jobname { get; set; }
        public Nullable<int> jobtype { get; set; }
        public Nullable<decimal> basicsalary { get; set; }
        public Nullable<decimal> housing { get; set; }
        public Nullable<decimal> allowncebsalary { get; set; }
        public Nullable<decimal> insursalary { get; set; }
        public Nullable<System.DateTime> empworkdate { get; set; }
        public Nullable<int> paytypeid { get; set; }
        public string paytypename { get; set; }
        public Nullable<int> paychartid { get; set; }
        public string empbankname { get; set; }
        public string empbankid { get; set; }
        public Nullable<int> annualvaction { get; set; }
        public Nullable<int> empchatid { get; set; }
        public Nullable<int> empstatus { get; set; }
        public string empstatusname { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hr_vactions> hr_vactions { get; set; }
    }
}
