//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMax.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_masterfiles
    {
        public int mersid { get; set; }
        public Nullable<int> masterid { get; set; }
        public string mastername { get; set; }
        public string masterename { get; set; }
        public Nullable<byte> mastertype { get; set; }
        public Nullable<int> mitemid { get; set; }
        public string mitemcode { get; set; }
        public string mitemname { get; set; }
        public Nullable<bool> mitembasic { get; set; }
        public Nullable<int> mitemtype { get; set; }
        public string mitemtyname { get; set; }
    }
}
