//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMax.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_vactions
    {
        public int vid { get; set; }
        public string vno { get; set; }
        public Nullable<System.DateTime> vdate { get; set; }
        public Nullable<int> empid { get; set; }
        public string empname { get; set; }
        public Nullable<int> vdays { get; set; }
        public Nullable<System.DateTime> vfromd { get; set; }
        public Nullable<System.DateTime> vtodate { get; set; }
        public string vnotes { get; set; }
        public Nullable<int> vnameid { get; set; }
        public string vname { get; set; }
        public Nullable<int> vnametype { get; set; }
        public Nullable<int> vapp { get; set; }
        public string vappname { get; set; }
        public string vuser { get; set; }
        public string vappuser { get; set; }
        public Nullable<int> vnature { get; set; }
        public string vnaturenmae { get; set; }
    
        public virtual hr_employees hr_employees { get; set; }
    }
}
