//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMax.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public p_order()
        {
            this.p_orderdtls = new HashSet<p_orderdtls>();
        }
    
        public int poid { get; set; }
        public string pono { get; set; }
        public string podocno { get; set; }
        public Nullable<System.DateTime> podate { get; set; }
        public Nullable<int> branchid { get; set; }
        public string branchname { get; set; }
        public Nullable<int> suppid { get; set; }
        public string suppname { get; set; }
        public Nullable<int> vattype { get; set; }
        public string vattypename { get; set; }
        public Nullable<decimal> totalop { get; set; }
        public Nullable<decimal> descp { get; set; }
        public Nullable<decimal> descv { get; set; }
        public Nullable<decimal> netbvat { get; set; }
        public Nullable<decimal> vatvalue { get; set; }
        public Nullable<decimal> netavat { get; set; }
        public string ponotes { get; set; }
        public string reqnos { get; set; }
        public string ouser { get; set; }
        public string fyaer { get; set; }
        public Nullable<bool> pinvc { get; set; }
    
        public virtual sys_branch sys_branch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<p_orderdtls> p_orderdtls { get; set; }
    }
}
