//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMax.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_orderdtls
    {
        public int podtlid { get; set; }
        public Nullable<int> poid { get; set; }
        public Nullable<int> itemid { get; set; }
        public Nullable<int> unitid { get; set; }
        public string unitname { get; set; }
        public Nullable<decimal> factor { get; set; }
        public Nullable<decimal> qty { get; set; }
        public Nullable<decimal> pprice { get; set; }
        public Nullable<decimal> pvalue { get; set; }
        public Nullable<decimal> descp { get; set; }
        public Nullable<decimal> descv { get; set; }
        public Nullable<decimal> pnet { get; set; }
        public string itemnotes { get; set; }
        public Nullable<bool> bonus { get; set; }
        public Nullable<int> branchid { get; set; }
        public Nullable<int> suppid { get; set; }
        public string suppname { get; set; }
        public Nullable<System.DateTime> podate { get; set; }
        public string fyaer { get; set; }
        public Nullable<decimal> vatvalue { get; set; }
    
        public virtual p_order p_order { get; set; }
    }
}
