//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMax.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_reqdtls
    {
        public int reqdtlis { get; set; }
        public Nullable<int> reqid { get; set; }
        public Nullable<int> itemid { get; set; }
        public Nullable<int> unitid { get; set; }
        public string unitname { get; set; }
        public Nullable<decimal> factor { get; set; }
        public Nullable<decimal> qty { get; set; }
        public string itemnotes { get; set; }
        public Nullable<int> branchid { get; set; }
        public Nullable<System.DateTime> reqdate { get; set; }
        public Nullable<bool> reqcase { get; set; }
        public string fyear { get; set; }
    
        public virtual p_request p_request { get; set; }
    }
}
