//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMax.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public p_supplier()
        {
            this.p_inv = new HashSet<p_inv>();
            this.st_itemunit = new HashSet<st_itemunit>();
        }
    
        public int suppid { get; set; }
        public string suppname { get; set; }
        public string suppename { get; set; }
        public Nullable<int> pgrpid { get; set; }
        public string pgrpname { get; set; }
        public string suppadd { get; set; }
        public string supptel { get; set; }
        public string suppmob { get; set; }
        public string suppvatno { get; set; }
        public string country { get; set; }
        public Nullable<int> suppchartid { get; set; }
        public Nullable<decimal> disc { get; set; }
        public Nullable<decimal> climit { get; set; }
        public Nullable<int> dlimit { get; set; }
        public Nullable<byte> supptype { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<p_inv> p_inv { get; set; }
        public virtual p_suppgroup p_suppgroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<st_itemunit> st_itemunit { get; set; }
    }
}
