//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMax.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class s_ItemHs2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public s_ItemHs2()
        {
            this.s_invdtls = new HashSet<s_invdtls>();
        }
    
        public int invdtlid2 { get; set; }
        public Nullable<int> sinvid { get; set; }
        public Nullable<int> itemid { get; set; }
        public Nullable<int> unitid { get; set; }
        public string unitname { get; set; }
        public Nullable<decimal> qty { get; set; }
        public Nullable<decimal> factor { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> icost { get; set; }
        public Nullable<decimal> value { get; set; }
        public Nullable<decimal> discp { get; set; }
        public Nullable<decimal> discvalue { get; set; }
        public Nullable<decimal> netvalue { get; set; }
        public Nullable<decimal> vatvalue { get; set; }
        public string itemnotes { get; set; }
        public Nullable<bool> bonus { get; set; }
        public Nullable<int> natureinv { get; set; }
        public Nullable<int> branchid { get; set; }
        public Nullable<System.DateTime> invdate { get; set; }
        public Nullable<int> custid { get; set; }
        public string sinvno { get; set; }
        public string custname { get; set; }
        public string branchname { get; set; }
        public string fyear { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<s_invdtls> s_invdtls { get; set; }
        public virtual s_inv s_inv { get; set; }
    }
}
