//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMax.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class s_orderdtls
    {
        public int sodtlid { get; set; }
        public Nullable<int> soid { get; set; }
        public Nullable<int> itemid { get; set; }
        public Nullable<int> unitid { get; set; }
        public string unitname { get; set; }
        public Nullable<decimal> factor { get; set; }
        public Nullable<decimal> qty { get; set; }
        public Nullable<decimal> sprice { get; set; }
        public Nullable<decimal> svalue { get; set; }
        public Nullable<decimal> discp { get; set; }
        public Nullable<decimal> discv { get; set; }
        public Nullable<decimal> snet { get; set; }
        public Nullable<decimal> vatvalue { get; set; }
        public string itemnotes { get; set; }
        public Nullable<bool> bonus { get; set; }
        public Nullable<int> branchid { get; set; }
        public Nullable<int> custid { get; set; }
        public string custname { get; set; }
        public Nullable<System.DateTime> sodate { get; set; }
        public Nullable<int> otype { get; set; }
        public string sono { get; set; }
        public string fyear { get; set; }
    
        public virtual s_order s_order { get; set; }
    }
}
