//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMax.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class st_inventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public st_inventory()
        {
            this.st_inventdlts = new HashSet<st_inventdlts>();
        }
    
        public int inventid { get; set; }
        public Nullable<System.DateTime> inventdate { get; set; }
        public string inventno { get; set; }
        public string inventdocno { get; set; }
        public Nullable<int> branchid { get; set; }
        public string branchname { get; set; }
        public string notes { get; set; }
        public string inventuser { get; set; }
        public Nullable<bool> postst { get; set; }
        public string fyear { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<st_inventdlts> st_inventdlts { get; set; }
    }
}
