//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMax.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_userdbord
    {
        public int id { get; set; }
        public Nullable<System.Guid> userid { get; set; }
        public Nullable<int> dbid { get; set; }
        public string dbname { get; set; }
        public string dblink { get; set; }
        public string dbvalue { get; set; }
        public Nullable<byte> dbtype { get; set; }
        public Nullable<System.Guid> useradminid { get; set; }
    }
}
