//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMax.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_docupload
    {
        public int docuid { get; set; }
        public Nullable<int> modid { get; set; }
        public string modname { get; set; }
        public string docpath { get; set; }
        public string docname { get; set; }
        public Nullable<int> docid { get; set; }
    }
}
