//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMax.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_company
    {
        public int compid { get; set; }
        public string compname { get; set; }
        public string compact { get; set; }
        public string compyear { get; set; }
        public string complegal { get; set; }
        public string comptel { get; set; }
        public string compmob { get; set; }
        public string compweb { get; set; }
        public string compemail { get; set; }
        public string compadd { get; set; }
        public string compmanager { get; set; }
        public string compvatno { get; set; }
        public string compnotes { get; set; }
        public string complogo { get; set; }
    }
}
