//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMax.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_paytype
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sys_paytype()
        {
            this.s_invpay = new HashSet<s_invpay>();
        }
    
        public int paytypeid { get; set; }
        public string paytname { get; set; }
        public string paytename { get; set; }
        public string modids { get; set; }
        public Nullable<decimal> feeds { get; set; }
        public Nullable<bool> paybasic { get; set; }
        public Nullable<byte> paychk { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<s_invpay> s_invpay { get; set; }
    }
}
